[package]
name = "heaspot"
version = "0.1.12"
description = "HeaSpot - Spotlight/Alfred cho Windows"
edition = "2021"

[lib]
name = "heaspot_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
arboard = "3"
image = { version = "0.25", default-features = false, features = ["png"] }
base64 = "0.22"
md-5 = "0.10"
sha1 = "0.10"
sha2 = "0.10"
aes-gcm = "0.10"
zip = { version = "2", default-features = false, features = ["deflate"] }
plist = "1"
walkdir = "2"
dirs = "5"
libloading = "0.8"
winreg = "0.52"
ureq = { version = "2", features = ["json"] }

[dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
    "Win32_System_Power",
    "Win32_System_Shutdown",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_Security",
    "Win32_Security_Cryptography",
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
